# Generated by Django 4.2.4 on 2023-08-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
