# Generated by Django 4.2.4 on 2023-09-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0007_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="featured",
            field=models.BooleanField(blank=None, db_index=True, default=1, null=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="menuitem",
            field=models.ForeignKey(
                blank=None,
                null=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonDRF.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=None, max_length=255, null=None),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                blank=None,
                null=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="LittleLemonDRF.category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                blank=None, db_index=True, decimal_places=2, max_digits=6, null=None
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(
                blank=None, db_index=True, max_length=255, null=None
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(blank=None, db_index=True, null=None),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(blank=None, db_index=True, default=0, null=None),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                blank=None, decimal_places=2, max_digits=6, null=None
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="menuitem",
            field=models.ForeignKey(
                blank=None,
                null=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="LittleLemonDRF.menuitem",
            ),
        ),
    ]
