# Generated by Django 4.2.4 on 2023-09-03 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0008_remove_cart_price_remove_cart_unit_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="inventory",
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
