# Generated by Django 4.2.4 on 2023-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0010_remove_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.DecimalField(
                blank=None, decimal_places=2, default=1, max_digits=3, null=None
            ),
            preserve_default=False,
        ),
    ]
