# Generated by Django 4.2.4 on 2023-09-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0011_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True, null=None),
        ),
    ]
