# Generated by Django 4.2.4 on 2023-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0013_orderitem_quantity_alter_orderitem_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("guest_number", models.IntegerField()),
                ("comment", models.CharField(max_length=1000)),
            ],
        ),
    ]
