# Generated by Django 4.2.4 on 2023-09-11 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0015_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="last_name",
        ),
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                null=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(
                blank=None,
                db_index=True,
                default=django.utils.timezone.now,
                max_length=100,
                null=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="time",
            field=models.SmallIntegerField(
                blank=None, db_index=True, default=12, null=None
            ),
            preserve_default=False,
        ),
    ]
