# Generated by Django 4.2.4 on 2023-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonDRF",
            "0016_remove_booking_comment_remove_booking_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(blank=None, db_index=True, null=None),
        ),
    ]
