# Generated by Django 4.2.4 on 2023-09-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0017_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.SmallIntegerField(),
        ),
    ]
