# Generated by Django 4.2.4 on 2023-09-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0018_alter_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.CharField(max_length=4),
        ),
    ]
