# Generated by Django 4.2.4 on 2023-09-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0019_alter_booking_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("date", "time")},
        ),
    ]
