# Generated by Django 4.2.4 on 2023-09-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonDRF", "0020_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
