# Generated by Django 4.2.4 on 2023-09-14 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=None, max_length=255, null=None)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                (
                    "menu_item_description",
                    models.TextField(default="", max_length=1000),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=None, db_index=True, max_length=255, null=None
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=None,
                        db_index=True,
                        decimal_places=2,
                        max_digits=6,
                        null=None,
                    ),
                ),
                ("inventory", models.SmallIntegerField()),
                ("featured", models.BooleanField(blank=None, db_index=True, null=None)),
                (
                    "category",
                    models.ForeignKey(
                        blank=None,
                        null=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        blank=None, db_index=True, default=0, null=None
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=None, decimal_places=2, max_digits=6, null=None
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, db_index=True, null=None)),
                (
                    "delivery_crew",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_crew",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=None, db_index=True, max_length=100, null=None
                    ),
                ),
                ("guests", models.SmallIntegerField()),
                ("date", models.DateField(blank=None, db_index=True, null=None)),
                ("time", models.CharField(max_length=4)),
            ],
            options={
                "unique_together": {("date", "time")},
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=None, decimal_places=2, max_digits=3, null=None
                    ),
                ),
                (
                    "menuitem",
                    models.ForeignKey(
                        blank=None,
                        null=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "menuitem")},
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=None, decimal_places=2, max_digits=3, null=None
                    ),
                ),
                (
                    "menuitem",
                    models.ForeignKey(
                        blank=None,
                        null=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("menuitem", "user")},
            },
        ),
    ]
